project_id = "ritdznjnleoeamhkdeeh"

[functions.validate-activation-key]
verify_jwt = false

[functions.verify-user-license]
verify_jwt = false

[functions.ffmpeg-start]
verify_jwt = false

[functions.ffmpeg-status]
verify_jwt = false

[functions.ffmpeg-stop]
verify_jwt = false

[functions.ffmpeg-transmit]
verify_jwt = false

[functions.ffmpeg-webhook]
verify_jwt = false
